services:
    - docker

before_install:
    - docker --version

script:
    - image="polinux/openvpn"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true # why does it return 1?
    - docker run --rm "$image" openssl version
